---
# tasks file for rust
- name: rust | Check if existing rustup
  shell: type rustup
  register: rustup_exists
  failed_when: false
  when:
    - ansible_system == "Linux"

- name: rust | Install tasks for Linux
  ansible.builtin.import_tasks:
    file: linux.yaml
  when:
    - rustup_exists.rc == 0
    - ansible_system == "Linux"