---
# tasks for Linux

- name: golang | Check if go exists
  shell: type go
  register: go_exists
  failed_when: false

- name: golang | Download the Go installer
  get_url:
    url: https://go.dev/dl/go1.18.linux-amd64.tar.gz
    dest: /tmp
  become: yes
  environment: "{{ proxy_env }}"
  when:
    - go_exists.rc != 0

- name: golang | Extract the Go package
  ansible.builtin.unarchive:
    src: /tmp/go1.18.linux-amd64.tar.gz
    dest: /usr/local
  become: yes
  when:
    - go_exists.rc != 0

- name: golang | Add go_env.sh to /etc/profile.d
  file:
    src: "{{ role_path }}/files/go_env.sh"
    dest: /etc/profile.d/go_env.sh
    force: yes
    state: hard
  become: yes
  

   