---
# tasks file for gping

- name: gping | Check if cargo exists
  shell: test cargo
  register: cargo_exists
  failed_when: false

- name: gping | Check if command exists
  shell: type gping
  register: command_exists
  failed_when: false
  when:
    - cargo_exists.rc == 0

- name: gping | Install the command
  shell: cargo install gping --locked
  environment: "{{ proxy_env }}"
  when:
    - cargo_exists.rc == 0
    - command_exists.rc != 0
