---
# tasks file for hyperfine

- name: hyperfine | Check if cargo exists
  shell: test cargo
  register: cargo_exists
  failed_when: false

- name: hyperfine | Check if command exists
  shell: type hyperfine
  register: command_exists
  failed_when: false
  when:
    - cargo_exists.rc == 0

- name: hyperfine | Install the command
  shell: cargo install hyperfine --locked
  environment: "{{ proxy_env }}"
  when:
    - cargo_exists.rc == 0
    - command_exists.rc != 0
