---
# tasks file for hexyl

- name: hexyl | Check if cargo exists
  shell: test cargo
  register: cargo_exists
  failed_when: false

- name: hexyl | Check if command exists
  shell: type hexyl
  register: command_exists
  failed_when: false
  when:
    - cargo_exists.rc == 0

- name: hexyl | Install the command
  shell: cargo install hexyl --locked
  environment: "{{ proxy_env }}"
  when:
    - cargo_exists.rc == 0
    - command_exists.rc != 0
