---
# tasks file for xh

- name: xh | Check if cargo exists
  shell: test cargo
  register: cargo_exists
  failed_when: false

- name: xh | Check if command exists
  shell: type xh
  register: command_exists
  failed_when: false
  when:
    - cargo_exists.rc == 0

- name: xh | Install the command
  shell: cargo install xh --locked
  environment: "{{ proxy_env }}"
  when:
    - cargo_exists.rc == 0
    - command_exists.rc != 0
