---
# tasks file for csview

- name: csview | Check if cargo exists
  shell: test cargo
  register: cargo_exists
  failed_when: false

- name: csview | Check if command exists
  shell: type csview
  register: command_exists
  failed_when: false
  when:
    - cargo_exists.rc == 0

- name: csview | Install the command
  shell: cargo install csview --locked
  when:
    - cargo_exists.rc == 0
    - command_exists.rc != 0
