---
# tasks file for cmake

- name: cmake | Check if cmake exists
  shell: type cmake
  register: cmake_exists
  failed_when: false
  when:
    - ansible_system == "Linux"

- name: cmake | Install package by homebrew
  homebrew:
    name:
      - ncurses
      - openssl@1.1
      - cmake
    update_homebrew: yes
  environment: "{{ proxy_env }}"
  when:
    - cmake_exists.rc != 0
    - ansible_system == "Linux"