---
# tasks file for clang

- name: clang | Check if clang exists
  shell: type clang
  register: clang_exists
  failed_when: false

- name: llvm | Install llvm by homebrew
  homebrew:
    name:
      - python@3.10
      - libedit
      - libffi
      - libxml2
      - ncurses
      - zlib
      - binutils
      - elfutils
      - gcc
      - llvm
    update_homebrew: yes
  when:
    clang_exists.rc != 0

- name: llvm | To use bundled libc++
  ansible.builtin.blockinfile:
    path: "{{ ansible_env.HOME }}/.profile"
    block: |
      LDFLAGS="-L/home/linuxbrew/.linuxbrew/opt/llvm/lib -Wl,-rpath,/home/linuxbrew/.linuxbrew/opt/llvm/lib"
    marker: "#{mark} ANSIBLE MANAGED BLOCK - llvm"
  when:
    - ansible_system == "Linux"
    - clang_exists.rc != 0