---
# tasks file for firacode

- name: firacode | Check if fontconfig exists
  shell: type fc-list
  register: fontconfig_exists
  failed_when: false
  when:
    - ansible_system == "Linux"

- name: firacode | Ensure fontconfig installed
  apt:
    pkg:
      - fontconfig
      - unzip
    update_cache: yes
  become: yes
  environment: "{{ proxy_env }}"
  when:
    - ansible_distribution == "Ubuntu"
    - fontconfig_exists.rc != 0

- name: firacode | Check if Fira Code Fonts exsists
  shell: bash -lc "fc-list"
  register: check_font
  changed_when: check_font.stdout.find('Fira Code') == -1
  when:
    - ansible_system == "Linux"

- name: firacode | Install Fira Code Nerd Font
  get_url:
    url: https://github.com/ryanoasis/nerd-fonts/releases/download/v2.1.0/FiraCode.zip
    dest: /tmp
  become: no
  environment: "{{ proxy_env }}"
  when:
    - check_font.changed
    - ansible_system == "Linux"

- name: firacode | Create directory for Fira Code Nerd Font
  file:
    path: /usr/share/fonts/firacode
    state: directory
    owner: root
    group: root
    mode: 0755
  register: create_font_directory
  become: yes
  when:
    - check_font.changed
    - ansible_system == "Linux"

- name: firacode | Unzip Fira Code Nerd Font
  ansible.builtin.unarchive:
    src: /tmp/FiraCode.zip
    dest: /usr/share/fonts/firacode
  become: yes
  when:
    - check_font.changed
    - ansible_system == "Linux"

- name: firacode | Update font caches
  shell: bash -lc "fc-cache -vf"
  changed_when: false

- name: firacode | Check if Fira Code Fonts exsists again
  shell: bash -lc "fc-list"
  changed_when: false
  failed_when: check_font.stdout.find('Fira Code') == -1
  when:
    - ansible_system == "Linux"
