---
# tasks for Ubuntu

- name: pwsh | Download Microsoft package repository
  get_url:
    url: https://packages.microsoft.com/config/ubuntu/18.04/packages-microsoft-prod.deb
    dest: /tmp/packages-microsoft-prod.deb
  become: yes
  environment: "{{ proxy_env }}"
  when:
    - ansible_distribution_version == "18.04"

- name: pwsh | Download Microsoft package repository
  get_url:
    url: https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb
    dest: /tmp/packages-microsoft-prod.deb
  become: yes
  environment: "{{ proxy_env }}"
  when:
    - ansible_distribution_version == "20.04"

- name: pwsh | Install Microsoft package repository
  apt:
    deb: /tmp/packages-microsoft-prod.deb
  become: yes
  environment: "{{ proxy_env }}"

- name: pwsh | Install PowerShell
  apt:
    pkg:
      - apt-transport-https
      - software-properties-common
      - powershell
    update_cache: yes
  become: yes
  environment: "{{ proxy_env }}"