---
# tasks file for onefetch

- name: onefetch | Check if cargo exists
  shell: test cargo
  register: cargo_exists
  failed_when: false

- name: onefetch | Check if command exists
  shell: type onefetch
  register: command_exists
  failed_when: false
  when:
    - cargo_exists.rc == 0

- name: onefetch | Install the command
  shell: cargo install onefetch --locked
  environment: "{{ proxy_env }}"
  when:
    - cargo_exists.rc == 0
    - command_exists.rc != 0
