---
# tasks file for dotnet6-sdk

- name: dotnet6-sdk | Install tasks for Ubuntu
  ansible.builtin.import_tasks:
    file: ubuntu.yaml
  when:
    - ansible_distribution == "Ubuntu"

- name: dotnet6-sdk | Install tasks for Amazon Linux 2
  ansible.builtin.import_tasks:
    file: amazon-linux-2.yaml
  when:
    - ansible_distribution == "Amazon"
    - ansible_distribution_major_version == "2"
