---
# tasks file for skim

- name: skim | Check if cargo exists
  shell: test cargo
  register: cargo_exists
  failed_when: false

- name: skim | Check if command exists
  shell: type skim
  register: command_exists
  failed_when: false
  when:
    - cargo_exists.rc == 0

- name: skim | Install the command
  shell: cargo install skim --locked
  environment: "{{ proxy_env }}"
  when:
    - cargo_exists.rc == 0
    - command_exists.rc != 0
