---
# tasks file for lsd

- name: lsd | Check if cargo exists
  shell: test cargo
  register: cargo_exists
  failed_when: false

- name: lsd | Check if command exists
  shell: type lsd
  register: command_exists
  failed_when: false
  when:
    - cargo_exists.rc == 0

- name: lsd | Install the command
  shell: cargo install lsd --locked
  environment: "{{ proxy_env }}"
  when:
    - cargo_exists.rc == 0
    - command_exists.rc != 0

- name: lsd | Check if bash instaled
  shell: type bash
  register: bash_exists
  when:
    - ansible_system == "Linux"

- name: lsd | Set alias and color for lsd
  ansible.builtin.blockinfile:
    path: "{{ ansible_env.HOME }}/.bashrc"
    block: |
      alias l='lsd -F'
      alias ll='lsd -alF'
      alias la='lsd -aF'
      alias lt='lsd --tree -F'
    marker: "#{mark} ANSIBLE MANAGED BLOCK - lsd"
  become: no
  when:
    - ansible_system == "Linux"
    - bash_exists.rc == 0