---
# tasks file for docker

- name: docker | Check if docker exists
  shell: type docker
  register: docker_exists
  failed_when: false

- name: docker | Install tasks for Ubuntu
  ansible.builtin.import_tasks:
    file: ubuntu.yaml
  when:
    - ansible_distribution == "Ubuntu"
