---
# tasks file for docker

- name: docker | Check if docker exists
  shell: type docker
  register: docker_exists
  failed_when: false

- name: docker | Install tasks for Ubuntu
  ansible.builtin.import_tasks:
    file: ubuntu.yaml
  when:
    - ansible_distribution == "Ubuntu"

- name: docker | Install tasks for Amazon Linux 2
  ansible.builtin.import_tasks:
    file: amazon-linux-2.yaml
  when:
    - ansible_distribution == "Amazon"
    - ansible_distribution_major_version == "2"

- name: docker | Enable service docker
  ansible.builtin.systemd:
    name: docker
    enabled: yes
  become: yes
  when:
    - ansible_system == "Linux"

- name: docker | Make sure a docker is running
  ansible.builtin.systemd:
    name: docker
    state: started
  become: yes
  when:
    - ansible_system == "Linux"


