---
# tasks file for starship

- name: starship | Check if starship exists
  ansible.builtin.shell: type starship
  register: starship_exists
  failed_when: false
  when:
    ansible_system == "Linux"

- name: starship | Install Starship using cargo
  homebrew:
    name:
      - starship
    update_homebrew: yes
  environment: "{{ proxy_env }}"
  become: no
  when:
    starship_exists.rc != 0

- name: starship | Check if bash exists
  shell: type bash
  register: bash_exists
  failed_when: false
  when:
    - ansible_system == "Linux"

- name: starship | Add the bootstrap code for starship
  blockinfile:
    path: "{{ ansible_env.HOME }}/.profile"
    block: |
      eval "$(starship init bash)"
    marker: "#{mark} ANSIBLE MANAGED BLOCK - starship"
  become: no
  when:
    - ansible_system == "Linux"
    - bash_exists.rc == 0

- name: starship | Check if PowerShell exists
  shell: type pwsh
  register: pwsh_exists 
  failed_when: false
  when:
    - ansible_system == "Linux"

- name: starship | Create PowerShell Profile directory
  file:
    path: "{{ ansible_env.HOME }}/.config/powershell"
    state: directory
    force: yes
  become: no
  when:
    - ansible_system == "Linux"
    - pwsh_exists.rc == 0

- name: starship | Create PowerShell Profile
  file:
    path: "{{ ansible_env.HOME }}/.config/powershell/Microsoft.PowerShell_profile.ps1"
    state: touch
    force: yes
  become: no
  when:
    - ansible_system == "Linux"
    - pwsh_exists.rc == 0

- name: starship | Add the bootstrap code for PowerShell
  blockinfile:
    path: "{{ ansible_env.HOME }}/.config/powershell/Microsoft.PowerShell_profile.ps1"
    block: |
      Invoke-Expression (&starship init powershell)
    marker: "#{mark} ANSIBLE MANAGED BLOCK - starship"
  become: no
  when:
    - ansible_system == "Linux"
    - pwsh_exists.rc == 0
  
- name: starship | Copy config file
  file:
    src: "{{ role_path }}/files/starship.toml"
    dest: "{{ ansible_env.HOME }}/.config/starship.toml"
    force: yes
    state: hard
  become: no
  when:
    - ansible_system == "Linux"
