---
# tasks file for watchexec-cli

- name: watchexec-cli | Check if cargo exists
  shell: test cargo
  register: cargo_exists
  failed_when: false

- name: watchexec-cli | Check if command exists
  shell: type watchexec
  register: command_exists
  failed_when: false
  when:
    - cargo_exists.rc == 0

- name: watchexec-cli | Install the command
  shell: cargo install watchexec-cli --locked
  environment: "{{ proxy_env }}"
  when:
    - cargo_exists.rc == 0
    - command_exists.rc != 0
