---
# tasks file for az

- name: az | Check if az installed
  shell: type az
  register: az_exists
  failed_when: false
  when:
    - ansible_system == "Linux"

- name: az | Import tasks for Ubuntu
  ansible.builtin.import_tasks:
    file: ubuntu.yaml
  when:
    - ansible_distribution == "Ubuntu"
    - az_exists.rc != 0
